<?php

namespace Database\Seeders\Models;

use App\Models\NotificationType;
use Illuminate\Database\Seeder;

class NotificationTypeSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'id' => 1,
                'user_type' => 'admin',
                'type' => 'order_placed_admin',
                'name' => 'Order Placed',
                'image' => null,
                'default_text' => 'Order: [[order_code]] has been Placed',
                'status' => 1,
                'addon' => null,
                'created_at' => '2024-05-14 15:35:09',
                'updated_at' => '2024-05-14 15:35:09',
            ],
            [
                'id' => 2,
                'user_type' => 'seller',
                'type' => 'order_placed_seller',
                'name' => 'Order Placed',
                'image' => null,
                'default_text' => 'Order: [[order_code]] has been Placed',
                'status' => 1,
                'addon' => null,
                'created_at' => '2024-05-14 15:35:09',
                'updated_at' => '2024-05-14 15:35:09',
            ],
            [
                'id' => 3,
                'user_type' => 'customer',
                'type' => 'order_placed_customer',
                'name' => 'Order Placed',
                'image' => null,
                'default_text' => 'Your Order: [[order_code]] has been Placed',
                'status' => 1,
                'addon' => null,
                'created_at' => '2024-05-14 15:35:09',
                'updated_at' => '2024-05-14 15:35:09',
            ],
            [
                'id' => 4,
                'user_type' => 'admin',
                'type' => 'order_confirmed_admin',
                'name' => 'Order Confirmed',
                'image' => null,
                'default_text' => 'Order: [[order_code]] has been Confirmed',
                'status' => 1,
                'addon' => null,
                'created_at' => '2024-05-14 15:35:09',
                'updated_at' => '2024-05-14 15:35:09',
            ],
            [
                'id' => 5,
                'user_type' => 'seller',
                'type' => 'order_confirmed_seller',
                'name' => 'Order Confirmed',
                'image' => null,
                'default_text' => 'Order: [[order_code]] has been Confirmed',
                'status' => 1,
                'addon' => null,
                'created_at' => '2024-05-14 15:35:09',
                'updated_at' => '2024-05-14 15:35:09',
            ],
            [
                'id' => 6,
                'user_type' => 'customer',
                'type' => 'order_confirmed_customer',
                'name' => 'Order Confirmed',
                'image' => null,
                'default_text' => 'Your Order: [[order_code]] has been Confirmed',
                'status' => 1,
                'addon' => null,
                'created_at' => '2024-05-14 15:35:09',
                'updated_at' => '2024-05-14 15:35:09',
            ],
            [
                'id' => 7,
                'user_type' => 'admin',
                'type' => 'order_picked_up_admin',
                'name' => 'Order Picked Up',
                'image' => null,
                'default_text' => 'Order: [[order_code]] has been picked up',
                'status' => 1,
                'addon' => null,
                'created_at' => '2024-05-14 15:35:09',
                'updated_at' => '2024-05-14 15:35:09',
            ],
            [
                'id' => 8,
                'user_type' => 'seller',
                'type' => 'order_picked_up_seller',
                'name' => 'Order Picked Up',
                'image' => null,
                'default_text' => 'Order: [[order_code]] has been picked up',
                'status' => 1,
                'addon' => null,
                'created_at' => '2024-05-14 15:35:09',
                'updated_at' => '2024-05-14 15:35:09',
            ],
            [
                'id' => 9,
                'user_type' => 'customer',
                'type' => 'order_picked_up_customer',
                'name' => 'Order Picked Up',
                'image' => null,
                'default_text' => 'Your Order: [[order_code]] has been picked up',
                'status' => 1,
                'addon' => null,
                'created_at' => '2024-05-14 15:35:09',
                'updated_at' => '2024-05-14 15:35:09',
            ],
            [
                'id' => 10,
                'user_type' => 'admin',
                'type' => 'order_on_the_way_admin',
                'name' => 'Order On the Way',
                'image' => null,
                'default_text' => 'Order: [[order_code]] is on the way',
                'status' => 1,
                'addon' => null,
                'created_at' => '2024-05-14 15:35:09',
                'updated_at' => '2024-05-14 15:35:09',
            ],
            [
                'id' => 11,
                'user_type' => 'seller',
                'type' => 'order_on_the_way_seller',
                'name' => 'Order On the Way',
                'image' => null,
                'default_text' => 'Order: [[order_code]] is on the way',
                'status' => 1,
                'addon' => null,
                'created_at' => '2024-05-14 15:35:09',
                'updated_at' => '2024-05-14 15:35:09',
            ],
            [
                'id' => 12,
                'user_type' => 'customer',
                'type' => 'order_on_the_way_customer',
                'name' => 'Order On the Way',
                'image' => null,
                'default_text' => 'Your Order: [[order_code]] is on the way',
                'status' => 1,
                'addon' => null,
                'created_at' => '2024-05-14 15:35:09',
                'updated_at' => '2024-05-14 15:35:09',
            ],
            [
                'id' => 13,
                'user_type' => 'admin',
                'type' => 'order_delivered_admin',
                'name' => 'Order Delivered',
                'image' => null,
                'default_text' => 'Order: [[order_code]] has been delivered',
                'status' => 1,
                'addon' => null,
                'created_at' => '2024-05-14 15:35:09',
                'updated_at' => '2024-05-14 15:35:09',
            ],
            [
                'id' => 14,
                'user_type' => 'seller',
                'type' => 'order_delivered_seller',
                'name' => 'Order Delivered',
                'image' => null,
                'default_text' => 'Order: [[order_code]] has been delivered',
                'status' => 1,
                'addon' => null,
                'created_at' => '2024-05-14 15:35:09',
                'updated_at' => '2024-05-14 15:35:09',
            ],
            [
                'id' => 15,
                'user_type' => 'customer',
                'type' => 'order_delivered_customer',
                'name' => 'Order Delivered',
                'image' => null,
                'default_text' => 'Your Order: [[order_code]] has been delivered',
                'status' => 1,
                'addon' => null,
                'created_at' => '2024-05-14 15:35:09',
                'updated_at' => '2024-05-14 15:35:09',
            ],
            [
                'id' => 16,
                'user_type' => 'admin',
                'type' => 'order_cancelled_admin',
                'name' => 'Order Cancelled',
                'image' => null,
                'default_text' => 'Order: [[order_code]] has been cancelled',
                'status' => 1,
                'addon' => null,
                'created_at' => '2024-05-14 15:35:09',
                'updated_at' => '2024-05-14 15:35:09',
            ],
            [
                'id' => 17,
                'user_type' => 'seller',
                'type' => 'order_cancelled_seller',
                'name' => 'Order Cancelled',
                'image' => null,
                'default_text' => 'Order: [[order_code]] has been cancelled',
                'status' => 1,
                'addon' => null,
                'created_at' => '2024-05-14 15:35:09',
                'updated_at' => '2024-05-14 15:35:09',
            ],
            [
                'id' => 18,
                'user_type' => 'customer',
                'type' => 'order_cancelled_customer',
                'name' => 'Order Cancelled',
                'image' => null,
                'default_text' => 'Your Order: [[order_code]] has been cancelled',
                'status' => 1,
                'addon' => null,
                'created_at' => '2024-05-14 15:35:09',
                'updated_at' => '2024-05-14 15:35:09',
            ],
            [
                'id' => 19,
                'user_type' => 'admin',
                'type' => 'order_paid_admin',
                'name' => 'Successful Payment',
                'image' => null,
                'default_text' => 'Payment for order: [[order_code]] is successful',
                'status' => 1,
                'addon' => null,
                'created_at' => '2024-05-14 15:35:09',
                'updated_at' => '2024-05-14 15:35:09',
            ],
            [
                'id' => 20,
                'user_type' => 'seller',
                'type' => 'order_paid_seller',
                'name' => 'Successful Payment',
                'image' => null,
                'default_text' => 'Payment for order: [[order_code]] is successful',
                'status' => 1,
                'addon' => null,
                'created_at' => '2024-05-14 15:35:09',
                'updated_at' => '2024-05-14 15:35:09',
            ],
            [
                'id' => 21,
                'user_type' => 'customer',
                'type' => 'order_paid_customer',
                'name' => 'Successful Payment',
                'image' => null,
                'default_text' => 'Your payment for order: [[order_code]] is successful',
                'status' => 1,
                'addon' => null,
                'created_at' => '2024-05-14 15:35:09',
                'updated_at' => '2024-05-14 15:35:09',
            ],
            [
                'id' => 22,
                'user_type' => 'admin',
                'type' => 'seller_product_upload',
                'name' => 'Seller Product Upload',
                'image' => null,
                'default_text' => 'Product : [[product_name]] is pending',
                'status' => 1,
                'addon' => null,
                'created_at' => '2024-05-14 15:35:09',
                'updated_at' => '2024-05-14 15:35:09',
            ],
            [
                'id' => 23,
                'user_type' => 'seller',
                'type' => 'seller_product_approved',
                'name' => 'Product Approved',
                'image' => null,
                'default_text' => 'Product : [[product_name]] is approved',
                'status' => 1,
                'addon' => null,
                'created_at' => '2024-05-14 15:35:09',
                'updated_at' => '2024-05-14 15:35:09',
            ],
            [
                'id' => 24,
                'user_type' => 'admin',
                'type' => 'seller_payout_request',
                'name' => 'Seller Payout Request',
                'image' => null,
                'default_text' => '[[shop_name]] request for payment : [[amount]]',
                'status' => 1,
                'addon' => null,
                'created_at' => '2024-05-14 15:35:09',
                'updated_at' => '2024-05-14 15:35:09',
            ],
            [
                'id' => 25,
                'user_type' => 'seller',
                'type' => 'seller_payout',
                'name' => 'Payout',
                'image' => null,
                'default_text' => '[[shop_name]] : payment [[amount]] is paid',
                'status' => 1,
                'addon' => null,
                'created_at' => '2024-05-14 15:35:09',
                'updated_at' => '2024-05-14 15:35:09',
            ],
            [
                'id' => 26,
                'user_type' => 'admin',
                'type' => 'shop_verify_request_submitted',
                'name' => 'Shop Verification Request Submitted',
                'image' => null,
                'default_text' => '[[shop_name]] submitted the verification request.',
                'status' => 1,
                'addon' => null,
                'created_at' => '2024-05-20 12:22:20',
                'updated_at' => '2024-05-20 12:22:20',
            ],
            [
                'id' => 27,
                'user_type' => 'seller',
                'type' => 'shop_verify_request_approved',
                'name' => 'Shop Verification Request Approved',
                'image' => null,
                'default_text' => 'Your shop verification request has been Approved.',
                'status' => 1,
                'addon' => null,
                'created_at' => '2024-05-20 12:22:20',
                'updated_at' => '2024-05-20 12:22:20',
            ],
            [
                'id' => 28,
                'user_type' => 'seller',
                'type' => 'shop_verify_request_rejected',
                'name' => 'Shop Verification Request Rejected',
                'image' => null,
                'default_text' => 'Your shop verification request has been Rejected.',
                'status' => 1,
                'addon' => null,
                'created_at' => '2024-05-20 12:22:20',
                'updated_at' => '2024-05-20 12:22:20',
            ],
            [
                'id' => 29,
                'user_type' => 'customer',
                'type' => 'complete_unpaid_order_payment',
                'name' => 'Complete Unpaid Order Payment',
                'image' => null,
                'default_text' => 'Your order: [[order_code]] is still not paid for. Kindly complete your payment.',
                'status' => 1,
                'addon' => null,
                'created_at' => '2024-08-22 05:45:04',
                'updated_at' => '2024-08-22 05:45:04',
            ],
        ];

        foreach ($data as $item) {
            NotificationType::updateOrCreate(['id' => $item['id']], $item);
        }
    }
}
