<?php

namespace Database\Seeders\Models;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /**
         * Command :
         * artisan seed:generate --model-mode --models=User
         *
         */


        $newData0 = \App\Models\User::create([
            'id' => 3,
            'referred_by' => null,
            'provider' => null,
            'provider_id' => null,
            'refresh_token' => null,
            'access_token' => null,
            'user_type' => 'seller',
            'name' => 'Mr. Seller',
            'email' => 'seller@example.com',
            'email_verified_at' => '2018-12-11 18:00:00',
            'verification_code' => null,
            'new_email_verificiation_code' => null,
            'password' => '$2y$10$eUKRlkmm2TAug75cfGQ4i.WoUbcJ2uVPqUlVkox.cv4CCyGEIMQEm',
            'remember_token' => 'GINywe8dds1cOqUAWuDMrkTss2DdqeXVRif3zJnhzu4Ezlpv5S58OXGFq2Lj',
            'device_token' => null,
            'avatar' => 'https://lh3.googleusercontent.com/-7OnRtLyua5Q/AAAAAAAAAAI/AAAAAAAADRk/VqWKMl4f8CI/photo.jpg?sz=50',
            'avatar_original' => null,
            'address' => 'Demo address',
            'country' => 'US',
            'state' => null,
            'city' => 'Demo city',
            'postal_code' => 1234,
            'phone' => null,
            'balance' => 0,
            'banned' => 0,
            'is_suspicious' => 0,
            'referral_code' => '3dLUoHsR1l',
            'customer_package_id' => null,
            'remaining_uploads' => null,
            'created_at' => '2018-10-07 04:42:57',
            'updated_at' => '2020-03-05 01:33:22',
        ]);
        $newData1 = \App\Models\User::create([
            'id' => 8,
            'referred_by' => null,
            'provider' => null,
            'provider_id' => null,
            'refresh_token' => null,
            'access_token' => null,
            'user_type' => 'customer',
            'name' => 'Mr. Customer',
            'email' => 'customer@example.com',
            'email_verified_at' => '2018-12-11 18:00:00',
            'verification_code' => null,
            'new_email_verificiation_code' => null,
            'password' => '$2y$10$eUKRlkmm2TAug75cfGQ4i.WoUbcJ2uVPqUlVkox.cv4CCyGEIMQEm',
            'remember_token' => '9ndcz5o7xgnuxctJIbvUQcP41QKmgnWCc7JDSnWdHOvipOP2AijpamCNafEe',
            'device_token' => null,
            'avatar' => 'https://lh3.googleusercontent.com/-7OnRtLyua5Q/AAAAAAAAAAI/AAAAAAAADRk/VqWKMl4f8CI/photo.jpg?sz=50',
            'avatar_original' => null,
            'address' => 'Demo address',
            'country' => 'US',
            'state' => null,
            'city' => 'Demo city',
            'postal_code' => 1234,
            'phone' => null,
            'balance' => 0,
            'banned' => 0,
            'is_suspicious' => 0,
            'referral_code' => '8zJTyXTlTT',
            'customer_package_id' => null,
            'remaining_uploads' => null,
            'created_at' => '2018-10-07 04:42:57',
            'updated_at' => '2020-03-03 04:26:11',
        ]);
        $newData2 = \App\Models\User::create([
            'id' => 11,
            'referred_by' => null,
            'provider' => null,
            'provider_id' => null,
            'refresh_token' => null,
            'access_token' => null,
            'user_type' => 'seller',
            'name' => 'Samuel Hoffman',
            'email' => 'seller1@example.com',
            'email_verified_at' => '2023-12-12 17:12:54',
            'verification_code' => null,
            'new_email_verificiation_code' => null,
            'password' => '$2y$10$gGAEaEclX4lUdKPpoIw4i.L/DpvAw0e/vhBY5fGCgdR/5Je8z7mUi',
            'remember_token' => null,
            'device_token' => null,
            'avatar' => null,
            'avatar_original' => 23,
            'address' => null,
            'country' => null,
            'state' => null,
            'city' => null,
            'postal_code' => null,
            'phone' => null,
            'balance' => 0,
            'banned' => 0,
            'is_suspicious' => 0,
            'referral_code' => null,
            'customer_package_id' => null,
            'remaining_uploads' => 0,
            'created_at' => '2023-12-12 17:06:54',
            'updated_at' => '2023-12-12 17:07:28',
        ]);
        $newData3 = \App\Models\User::create([
            'id' => 12,
            'referred_by' => null,
            'provider' => null,
            'provider_id' => null,
            'refresh_token' => null,
            'access_token' => null,
            'user_type' => 'seller',
            'name' => 'Gareth Gilbert',
            'email' => 'seller2@example.com',
            'email_verified_at' => '2024-01-09 14:01:59',
            'verification_code' => null,
            'new_email_verificiation_code' => null,
            'password' => '$2y$10$1h1Ym/pjUlG5XGfgNrMDMuygwY99du9MvnQWCNYhh1TlsNT3uirm6',
            'remember_token' => null,
            'device_token' => null,
            'avatar' => null,
            'avatar_original' => null,
            'address' => null,
            'country' => null,
            'state' => null,
            'city' => null,
            'postal_code' => null,
            'phone' => null,
            'balance' => 0,
            'banned' => 0,
            'is_suspicious' => 0,
            'referral_code' => null,
            'customer_package_id' => null,
            'remaining_uploads' => 0,
            'created_at' => '2024-01-09 14:13:59',
            'updated_at' => '2024-01-09 14:13:59',
        ]);
        $newData4 = \App\Models\User::create([
            'id' => 13,
            'referred_by' => null,
            'provider' => null,
            'provider_id' => null,
            'refresh_token' => null,
            'access_token' => null,
            'user_type' => 'seller',
            'name' => 'Rahim Underwood',
            'email' => 'seller3@example.com',
            'email_verified_at' => '2024-01-09 14:01:40',
            'verification_code' => null,
            'new_email_verificiation_code' => null,
            'password' => '$2y$10$cE5mfsKm9LFDkv8MGEMtlu.Pe/X01OfhSwrfSxAVbGOa9Vl5BmOPe',
            'remember_token' => null,
            'device_token' => null,
            'avatar' => null,
            'avatar_original' => null,
            'address' => null,
            'country' => null,
            'state' => null,
            'city' => null,
            'postal_code' => null,
            'phone' => null,
            'balance' => 0,
            'banned' => 0,
            'is_suspicious' => 0,
            'referral_code' => null,
            'customer_package_id' => null,
            'remaining_uploads' => 0,
            'created_at' => '2024-01-09 14:16:40',
            'updated_at' => '2024-01-09 14:16:40',
        ]);
        $newData5 = \App\Models\User::create([
            'id' => 14,
            'referred_by' => null,
            'provider' => null,
            'provider_id' => null,
            'refresh_token' => null,
            'access_token' => null,
            'user_type' => 'seller',
            'name' => 'Deanna Velez',
            'email' => 'seller4@example.com',
            'email_verified_at' => '2024-01-09 14:01:07',
            'verification_code' => null,
            'new_email_verificiation_code' => null,
            'password' => '$2y$10$QCsxNi3afWQ6khhGN3hatuf1cDZO4WNJLR4LSqiBYmm4HLrGmaAzy',
            'remember_token' => null,
            'device_token' => null,
            'avatar' => null,
            'avatar_original' => null,
            'address' => null,
            'country' => null,
            'state' => null,
            'city' => null,
            'postal_code' => null,
            'phone' => null,
            'balance' => 0,
            'banned' => 0,
            'is_suspicious' => 0,
            'referral_code' => null,
            'customer_package_id' => null,
            'remaining_uploads' => 0,
            'created_at' => '2024-01-09 14:18:07',
            'updated_at' => '2024-01-09 14:18:07',
        ]);
        $newData6 = \App\Models\User::create([
            'id' => 15,
            'referred_by' => null,
            'provider' => null,
            'provider_id' => null,
            'refresh_token' => null,
            'access_token' => null,
            'user_type' => 'admin',
            'name' => 'Tanbir Ahmed',
            'email' => 'admin@mail.com',
            'email_verified_at' => '2025-08-24 07:08:27',
            'verification_code' => null,
            'new_email_verificiation_code' => null,
            'password' => '$2y$10$gGAEaEclX4lUdKPpoIw4i.L/DpvAw0e/vhBY5fGCgdR/5Je8z7mUi',
            'remember_token' => null,
            'device_token' => null,
            'avatar' => null,
            'avatar_original' => null,
            'address' => null,
            'country' => null,
            'state' => null,
            'city' => null,
            'postal_code' => null,
            'phone' => null,
            'balance' => 0,
            'banned' => 0,
            'is_suspicious' => 0,
            'referral_code' => null,
            'customer_package_id' => null,
            'remaining_uploads' => 0,
            'created_at' => '2025-08-24 07:12:27',
            'updated_at' => '2025-08-24 07:12:27',
        ]);
        $newData7 = \App\Models\User::create([
            'id' => 16,
            'referred_by' => null,
            'provider' => null,
            'provider_id' => null,
            'refresh_token' => null,
            'access_token' => null,
            'user_type' => 'customer',
            'name' => 'Tanbir',
            'email' => 'tanbir@imjol.com',
            'email_verified_at' => '2025-08-25 06:08:08',
            'verification_code' => null,
            'new_email_verificiation_code' => null,
            'password' => '$2y$10$sIFmL/uxAow2tMuesTEA2Ov4dYE8u6YG0z270Jb6WaKasKuNZ2Euq',
            'remember_token' => null,
            'device_token' => null,
            'avatar' => null,
            'avatar_original' => null,
            'address' => null,
            'country' => null,
            'state' => null,
            'city' => null,
            'postal_code' => null,
            'phone' => null,
            'balance' => 0,
            'banned' => 0,
            'is_suspicious' => 0,
            'referral_code' => null,
            'customer_package_id' => null,
            'remaining_uploads' => 0,
            'created_at' => '2025-08-25 06:13:08',
            'updated_at' => '2025-08-25 06:13:08',
        ]);

        $modelHasRole = DB::table('model_has_roles')->insert([
            'role_id' => 1,
            'model_type' => 'App\Models\User',
            'model_id' => 15,
        ]);
    }
}
